[package]
name = "space-observers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.10"
quad-net = "0.1.1"
sapp-jsutils = "0.1"
futures = "0.3.17"